### PR TITLE
add issuer links

### PR DESCRIPTION
**Pull request by mozkeeler**
How does this look? In particular, is "Direct Link" clear enough?

### CODE REVIEW

**Comment by mozkeeler** [comment]
Whoops - I haven't deployed this yet. Let me re-generate the DB/site files with the most recent CT log info.

**Comment by mozkeeler** [comment]
Ok - should be good to go now at the same url.

**Comment by monicachew** [comment]
This is a good start, but it's got some usability issues. I think it would be better to have the link update when autocomplete finishes. That way the URL is always correct (you can't end up on a URL that doesn't match what's being shown) and you can get rid of the "Direct link" field.

$('#autocomplete').autocomplete({
  source: filteredIssuers,
  minLength: 0,
  select: function(event, suggestion) {
    makeChart(suggestion.item.value);
    // Update link here?
  }
});

**Comment by mozkeeler** [comment]
I'm not sure if this is what you meant, but the most recent change updates the location shown in the urlbar such that if you navigated to that url, it would show what the page currently shows.

**Comment by monicachew** [comment]
Yep, that's what I meant. I think now there's no use for the "Direct link"  link, unless I'm missing something.

**Comment by mozkeeler** [comment]
Sounds good - I removed the link.

**Comment by monicachew** [comment]
Looks great, thanks!

**Pull request merged**
