### PR TITLE
misc. dashboard improvements

### PR DESCRIPTION
**Pull request by mozkeeler**
Let me know if you think I should change the fix for #50 to truncating in db2json.js instead of index.html.

### CODE REVIEW

**Comment by monicachew** [comment]
It looks good, but I think it's better to truncate in db2json -- you get to get rid of a lot of tooltip code.

**Comment by monicachew** [comment]
I think SELECT printf("%.3f", scorefield) might work

**Comment by mozkeeler** [comment]
Ok - this is live at https://people.mozilla.org/~dkeeler/dashboard/

**Comment by monicachew** [comment]
Thanks! Is the dropdown thing you added in a different branch?

**Comment by mozkeeler** [comment]
Thanks! The dropdown is coming soon.

**Pull request merged**
